CREATE TABLE IF NOT EXISTS `minet`.`user` (
    `id` INT PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `password` VARCHAR(100) NOT NULL,
    `avatar` VARCHAR(100),
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `minet`.`user_wallet` (
`id` INT NOT NULL auto_increment,
`user_id` INT NOT NULL,
`wallet_id` INT NOT NULL,
PRIMARY KEY(`id`),
KEY `FK_USER_WALLET_idx` (`user_id`),
CONSTRAINT `FK_USER_WALLET` FOREIGN KEY (`user_id`) 
REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `minet`.`user_transaction` (
`id` INT NOT NULL auto_increment,
`user_id` INT NOT NULL,
`transaction_id` INT NOT NULL,
PRIMARY KEY(`id`),
KEY `FK_USER_TRANSACTION_idx` (`user_id`),
CONSTRAINT `FK_USER_TRANSACTION` FOREIGN KEY (`user_id`) 
REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `minet`.`watchlist` (
`id` INT NOT NULL auto_increment,
`user_id` INT NOT NULL,
`currency_id` VARCHAR(40) NOT NULL,
PRIMARY KEY(`id`),
KEY `FK_USER_WATCHLIST_idx` (`user_id`),
CONSTRAINT `FK_USER_WATCHLIST` FOREIGN KEY (`user_id`) 
KEY `FK_WATCHLIST_CURRENCY_idx` (`currency_id`),
CONSTRAINT `FK_WATCHLIST_CURRENCY` FOREIGN KEY (`currency_id`) 
REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;